// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package com.xd.protobuf;

public final class Mobile {
  private Mobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MobilePhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xd.protobuf.MobilePhone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string brand = 1;</code>
     */
    boolean hasBrand();
    /**
     * <code>required string brand = 1;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>required string brand = 1;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
     */
    boolean hasHardware();
    /**
     * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
     */
    com.xd.protobuf.Mobile.Hardware getHardware();
    /**
     * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
     */
    com.xd.protobuf.Mobile.HardwareOrBuilder getHardwareOrBuilder();

    /**
     * <code>repeated string software = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getSoftwareList();
    /**
     * <code>repeated string software = 3;</code>
     */
    int getSoftwareCount();
    /**
     * <code>repeated string software = 3;</code>
     */
    java.lang.String getSoftware(int index);
    /**
     * <code>repeated string software = 3;</code>
     */
    com.google.protobuf.ByteString
        getSoftwareBytes(int index);
  }
  /**
   * Protobuf type {@code com.xd.protobuf.MobilePhone}
   */
  public static final class MobilePhone extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.xd.protobuf.MobilePhone)
      MobilePhoneOrBuilder {
    // Use MobilePhone.newBuilder() to construct.
    private MobilePhone(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MobilePhone(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MobilePhone defaultInstance;
    public static MobilePhone getDefaultInstance() {
      return defaultInstance;
    }

    public MobilePhone getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MobilePhone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              brand_ = bs;
              break;
            }
            case 18: {
              com.xd.protobuf.Mobile.Hardware.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = hardware_.toBuilder();
              }
              hardware_ = input.readMessage(com.xd.protobuf.Mobile.Hardware.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hardware_);
                hardware_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                software_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              software_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = software_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_MobilePhone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_MobilePhone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xd.protobuf.Mobile.MobilePhone.class, com.xd.protobuf.Mobile.MobilePhone.Builder.class);
    }

    public static com.google.protobuf.Parser<MobilePhone> PARSER =
        new com.google.protobuf.AbstractParser<MobilePhone>() {
      public MobilePhone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MobilePhone(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MobilePhone> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BRAND_FIELD_NUMBER = 1;
    private java.lang.Object brand_;
    /**
     * <code>required string brand = 1;</code>
     */
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string brand = 1;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string brand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HARDWARE_FIELD_NUMBER = 2;
    private com.xd.protobuf.Mobile.Hardware hardware_;
    /**
     * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
     */
    public boolean hasHardware() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
     */
    public com.xd.protobuf.Mobile.Hardware getHardware() {
      return hardware_;
    }
    /**
     * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
     */
    public com.xd.protobuf.Mobile.HardwareOrBuilder getHardwareOrBuilder() {
      return hardware_;
    }

    public static final int SOFTWARE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList software_;
    /**
     * <code>repeated string software = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSoftwareList() {
      return software_;
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public int getSoftwareCount() {
      return software_.size();
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public java.lang.String getSoftware(int index) {
      return software_.get(index);
    }
    /**
     * <code>repeated string software = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSoftwareBytes(int index) {
      return software_.getByteString(index);
    }

    private void initFields() {
      brand_ = "";
      hardware_ = com.xd.protobuf.Mobile.Hardware.getDefaultInstance();
      software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBrand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHardware()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHardware().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBrandBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, hardware_);
      }
      for (int i = 0; i < software_.size(); i++) {
        output.writeBytes(3, software_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBrandBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, hardware_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < software_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(software_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSoftwareList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xd.protobuf.Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xd.protobuf.Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xd.protobuf.Mobile.MobilePhone prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xd.protobuf.MobilePhone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xd.protobuf.MobilePhone)
        com.xd.protobuf.Mobile.MobilePhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_MobilePhone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_MobilePhone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xd.protobuf.Mobile.MobilePhone.class, com.xd.protobuf.Mobile.MobilePhone.Builder.class);
      }

      // Construct using com.xd.protobuf.Mobile.MobilePhone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHardwareFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        brand_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (hardwareBuilder_ == null) {
          hardware_ = com.xd.protobuf.Mobile.Hardware.getDefaultInstance();
        } else {
          hardwareBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_MobilePhone_descriptor;
      }

      public com.xd.protobuf.Mobile.MobilePhone getDefaultInstanceForType() {
        return com.xd.protobuf.Mobile.MobilePhone.getDefaultInstance();
      }

      public com.xd.protobuf.Mobile.MobilePhone build() {
        com.xd.protobuf.Mobile.MobilePhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xd.protobuf.Mobile.MobilePhone buildPartial() {
        com.xd.protobuf.Mobile.MobilePhone result = new com.xd.protobuf.Mobile.MobilePhone(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brand_ = brand_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (hardwareBuilder_ == null) {
          result.hardware_ = hardware_;
        } else {
          result.hardware_ = hardwareBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = software_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.software_ = software_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xd.protobuf.Mobile.MobilePhone) {
          return mergeFrom((com.xd.protobuf.Mobile.MobilePhone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xd.protobuf.Mobile.MobilePhone other) {
        if (other == com.xd.protobuf.Mobile.MobilePhone.getDefaultInstance()) return this;
        if (other.hasBrand()) {
          bitField0_ |= 0x00000001;
          brand_ = other.brand_;
          onChanged();
        }
        if (other.hasHardware()) {
          mergeHardware(other.getHardware());
        }
        if (!other.software_.isEmpty()) {
          if (software_.isEmpty()) {
            software_ = other.software_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSoftwareIsMutable();
            software_.addAll(other.software_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBrand()) {
          
          return false;
        }
        if (!hasHardware()) {
          
          return false;
        }
        if (!getHardware().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xd.protobuf.Mobile.MobilePhone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xd.protobuf.Mobile.MobilePhone) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object brand_ = "";
      /**
       * <code>required string brand = 1;</code>
       */
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brand_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }

      private com.xd.protobuf.Mobile.Hardware hardware_ = com.xd.protobuf.Mobile.Hardware.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xd.protobuf.Mobile.Hardware, com.xd.protobuf.Mobile.Hardware.Builder, com.xd.protobuf.Mobile.HardwareOrBuilder> hardwareBuilder_;
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      public boolean hasHardware() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      public com.xd.protobuf.Mobile.Hardware getHardware() {
        if (hardwareBuilder_ == null) {
          return hardware_;
        } else {
          return hardwareBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      public Builder setHardware(com.xd.protobuf.Mobile.Hardware value) {
        if (hardwareBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hardware_ = value;
          onChanged();
        } else {
          hardwareBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      public Builder setHardware(
          com.xd.protobuf.Mobile.Hardware.Builder builderForValue) {
        if (hardwareBuilder_ == null) {
          hardware_ = builderForValue.build();
          onChanged();
        } else {
          hardwareBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      public Builder mergeHardware(com.xd.protobuf.Mobile.Hardware value) {
        if (hardwareBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              hardware_ != com.xd.protobuf.Mobile.Hardware.getDefaultInstance()) {
            hardware_ =
              com.xd.protobuf.Mobile.Hardware.newBuilder(hardware_).mergeFrom(value).buildPartial();
          } else {
            hardware_ = value;
          }
          onChanged();
        } else {
          hardwareBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      public Builder clearHardware() {
        if (hardwareBuilder_ == null) {
          hardware_ = com.xd.protobuf.Mobile.Hardware.getDefaultInstance();
          onChanged();
        } else {
          hardwareBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      public com.xd.protobuf.Mobile.Hardware.Builder getHardwareBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHardwareFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      public com.xd.protobuf.Mobile.HardwareOrBuilder getHardwareOrBuilder() {
        if (hardwareBuilder_ != null) {
          return hardwareBuilder_.getMessageOrBuilder();
        } else {
          return hardware_;
        }
      }
      /**
       * <code>required .com.xd.protobuf.Hardware hardware = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.xd.protobuf.Mobile.Hardware, com.xd.protobuf.Mobile.Hardware.Builder, com.xd.protobuf.Mobile.HardwareOrBuilder> 
          getHardwareFieldBuilder() {
        if (hardwareBuilder_ == null) {
          hardwareBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xd.protobuf.Mobile.Hardware, com.xd.protobuf.Mobile.Hardware.Builder, com.xd.protobuf.Mobile.HardwareOrBuilder>(
                  getHardware(),
                  getParentForChildren(),
                  isClean());
          hardware_ = null;
        }
        return hardwareBuilder_;
      }

      private com.google.protobuf.LazyStringList software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSoftwareIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          software_ = new com.google.protobuf.LazyStringArrayList(software_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSoftwareList() {
        return software_.getUnmodifiableView();
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public int getSoftwareCount() {
        return software_.size();
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public java.lang.String getSoftware(int index) {
        return software_.get(index);
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSoftwareBytes(int index) {
        return software_.getByteString(index);
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder setSoftware(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addSoftware(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addAllSoftware(
          java.lang.Iterable<java.lang.String> values) {
        ensureSoftwareIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, software_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder clearSoftware() {
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       */
      public Builder addSoftwareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.xd.protobuf.MobilePhone)
    }

    static {
      defaultInstance = new MobilePhone(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.xd.protobuf.MobilePhone)
  }

  public interface HardwareOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xd.protobuf.Hardware)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 rom = 1;</code>
     */
    boolean hasRom();
    /**
     * <code>required int32 rom = 1;</code>
     */
    int getRom();

    /**
     * <code>required int32 ram = 2;</code>
     */
    boolean hasRam();
    /**
     * <code>required int32 ram = 2;</code>
     */
    int getRam();

    /**
     * <code>required int32 size = 3;</code>
     */
    boolean hasSize();
    /**
     * <code>required int32 size = 3;</code>
     */
    int getSize();
  }
  /**
   * Protobuf type {@code com.xd.protobuf.Hardware}
   */
  public static final class Hardware extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.xd.protobuf.Hardware)
      HardwareOrBuilder {
    // Use Hardware.newBuilder() to construct.
    private Hardware(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Hardware(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Hardware defaultInstance;
    public static Hardware getDefaultInstance() {
      return defaultInstance;
    }

    public Hardware getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Hardware(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rom_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ram_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              size_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_Hardware_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_Hardware_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xd.protobuf.Mobile.Hardware.class, com.xd.protobuf.Mobile.Hardware.Builder.class);
    }

    public static com.google.protobuf.Parser<Hardware> PARSER =
        new com.google.protobuf.AbstractParser<Hardware>() {
      public Hardware parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hardware(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Hardware> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ROM_FIELD_NUMBER = 1;
    private int rom_;
    /**
     * <code>required int32 rom = 1;</code>
     */
    public boolean hasRom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rom = 1;</code>
     */
    public int getRom() {
      return rom_;
    }

    public static final int RAM_FIELD_NUMBER = 2;
    private int ram_;
    /**
     * <code>required int32 ram = 2;</code>
     */
    public boolean hasRam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 ram = 2;</code>
     */
    public int getRam() {
      return ram_;
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>required int32 size = 3;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 size = 3;</code>
     */
    public int getSize() {
      return size_;
    }

    private void initFields() {
      rom_ = 0;
      ram_ = 0;
      size_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRam()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ram_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, size_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ram_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xd.protobuf.Mobile.Hardware parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xd.protobuf.Mobile.Hardware parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xd.protobuf.Mobile.Hardware parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xd.protobuf.Mobile.Hardware parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xd.protobuf.Mobile.Hardware parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xd.protobuf.Mobile.Hardware parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xd.protobuf.Mobile.Hardware parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xd.protobuf.Mobile.Hardware parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xd.protobuf.Mobile.Hardware parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xd.protobuf.Mobile.Hardware parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xd.protobuf.Mobile.Hardware prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xd.protobuf.Hardware}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xd.protobuf.Hardware)
        com.xd.protobuf.Mobile.HardwareOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_Hardware_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_Hardware_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xd.protobuf.Mobile.Hardware.class, com.xd.protobuf.Mobile.Hardware.Builder.class);
      }

      // Construct using com.xd.protobuf.Mobile.Hardware.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ram_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xd.protobuf.Mobile.internal_static_com_xd_protobuf_Hardware_descriptor;
      }

      public com.xd.protobuf.Mobile.Hardware getDefaultInstanceForType() {
        return com.xd.protobuf.Mobile.Hardware.getDefaultInstance();
      }

      public com.xd.protobuf.Mobile.Hardware build() {
        com.xd.protobuf.Mobile.Hardware result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xd.protobuf.Mobile.Hardware buildPartial() {
        com.xd.protobuf.Mobile.Hardware result = new com.xd.protobuf.Mobile.Hardware(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rom_ = rom_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ram_ = ram_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xd.protobuf.Mobile.Hardware) {
          return mergeFrom((com.xd.protobuf.Mobile.Hardware)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xd.protobuf.Mobile.Hardware other) {
        if (other == com.xd.protobuf.Mobile.Hardware.getDefaultInstance()) return this;
        if (other.hasRom()) {
          setRom(other.getRom());
        }
        if (other.hasRam()) {
          setRam(other.getRam());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRom()) {
          
          return false;
        }
        if (!hasRam()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xd.protobuf.Mobile.Hardware parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xd.protobuf.Mobile.Hardware) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rom_ ;
      /**
       * <code>required int32 rom = 1;</code>
       */
      public boolean hasRom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rom = 1;</code>
       */
      public int getRom() {
        return rom_;
      }
      /**
       * <code>required int32 rom = 1;</code>
       */
      public Builder setRom(int value) {
        bitField0_ |= 0x00000001;
        rom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rom = 1;</code>
       */
      public Builder clearRom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rom_ = 0;
        onChanged();
        return this;
      }

      private int ram_ ;
      /**
       * <code>required int32 ram = 2;</code>
       */
      public boolean hasRam() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 ram = 2;</code>
       */
      public int getRam() {
        return ram_;
      }
      /**
       * <code>required int32 ram = 2;</code>
       */
      public Builder setRam(int value) {
        bitField0_ |= 0x00000002;
        ram_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ram = 2;</code>
       */
      public Builder clearRam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ram_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>required int32 size = 3;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 size = 3;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>required int32 size = 3;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000004;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 size = 3;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.xd.protobuf.Hardware)
    }

    static {
      defaultInstance = new Hardware(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.xd.protobuf.Hardware)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xd_protobuf_MobilePhone_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xd_protobuf_MobilePhone_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xd_protobuf_Hardware_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xd_protobuf_Hardware_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mobile.proto\022\017com.xd.protobuf\"[\n\013Mobil" +
      "ePhone\022\r\n\005brand\030\001 \002(\t\022+\n\010hardware\030\002 \002(\0132" +
      "\031.com.xd.protobuf.Hardware\022\020\n\010software\030\003" +
      " \003(\t\"2\n\010Hardware\022\013\n\003rom\030\001 \002(\005\022\013\n\003ram\030\002 \002" +
      "(\005\022\014\n\004size\030\003 \002(\005B\031\n\017com.xd.protobufB\006Mob" +
      "ile"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xd_protobuf_MobilePhone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xd_protobuf_MobilePhone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_xd_protobuf_MobilePhone_descriptor,
        new java.lang.String[] { "Brand", "Hardware", "Software", });
    internal_static_com_xd_protobuf_Hardware_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xd_protobuf_Hardware_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_xd_protobuf_Hardware_descriptor,
        new java.lang.String[] { "Rom", "Ram", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
